import { CardBalance, CardPreviousOrder, ImageProduct, SlickProduct } from "@/components";
import { NextPage } from "next";
import Head from "next/head";
import { Roboto } from 'next/font/google'
import { useEffect, useState } from "react";

const roboto = Roboto({
  weight: '700',
  subsets: ['latin'],
})

const Index: NextPage = () => {
  const [user, setUser] = useState<any>(null);

  useEffect(() => {
    fetch("https://belaundry-api.sebaris.link/platform/user/info",{
      headers: {
        token: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoxLCJpYXQiOjE2OTEyMjM4NDN9.Vdtbk-IDZ7ldPhFveVdi7NQWSlbG7JP-rH40PtT1_kc`,
      }
    })
    .then((res) => {
      return res.json();
    })
    .then((data) => {
      setUser(data?.response);
    })
    .catch((err) => {
      return console.error(err);
    });
  }, []);
  
  return (
    <>
      <Head>
        <title>be-launrdy</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <div>
        <div className="pony"></div>
        <section className="balance px-9">
          <h1 className="text-white mb-6">Welcome, {user?.name}</h1>
          <CardBalance/>
        </section>
        <section className="px-9 mt-10">
          <h1 className={"mb-3 "+roboto.className}>PREVIOUS ORDER</h1>
          <CardPreviousOrder/>
        </section>
        <section className="px-9 mt-10">
          <h1 className={"mb-3 "+roboto.className}>YOUR MOST ORDERED</h1>
          <ImageProduct image="/assets/images/dry-cleaning.png" width={500} height={214} title="Dry Cleaning" desc="12x | total of $ 4.000" />
        </section>
        <section className="pl-9 pb-9 mt-10">
          <h1 className={"mb-3 "+roboto.className}>OUR LATEST PRODUCT</h1>
          <div>
            <SlickProduct />
          </div>
        </section>
      </div>
    </>
  );
};

export default Index;
